---
- name: provisioning an Ec2 instance using urvashi-ansible
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning
  vars: 
    keypair: urvi_KeyPair
    instance_type: t2.micro
    image: ami-007855ac798b5175e
    wait: yes
    group: webserver
    count: 1
    region: us-east-1
    security_group: sg-0a76a77c0b2560425
  tasks:
  - name: Launch a new ec2 instance
    local_action: ec2
                 #group: {{security_group}}
                  instance_type: {{instance_type}} 
                  image: {{image}}
                  wait: true
                  region: {{region}}
                  keypair: {{keypair}}
                  count: {{count}}
    register: ec2
    -name: add tags to ec2 instance
    local_action: ec2_tag_resource={{item.id}} region:{{region}} state:present
    with_items: "{{ec2.instance}}"
    args:
      tags:
        Name: MyurvashiEc2instance